version: '3'

services: 
    balanced-gg-react:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: balanced-gg-react:latest
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=8080
            # Can only get dev server working on port 8080 for WSL2
            # Feel free to run on another port verify that it's just 
            # a problem on my machine
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app
            - /app/node_modules