version: '3'

services: 
    balanced-gg-react:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: balanced-gg-react:latest
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3000:3000"
        volumes:
            - ./app:/app
            - /app/node_modules